import Head from 'next/head';
import IntroHeader from '@/components/introHeader';
import About from '@/components/about';
import Work from '@/components/work';

export default function Home() {
  return (
    <div className='bg-zinc-900 bg-dotted-spacing-8 bg-dotted-zinc-700 h-full'>
      <Head>
        <title>Aryan Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <IntroHeader />
      <hr  className=" h-0.5 mx-auto my-2 bg-zinc-600 w-11/12 border-0 rounded " />
      <About />
      <hr  className="h-0.5 mx-auto my-2 bg-zinc-600 w-11/12 border-0 rounded " />
      <Work />
    </div>
  );
}
